// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eu.getintheloop.sample

case class GetWeather(City: Option[String])


case class GetWeatherResponse(GetWeatherResult: Option[String])


trait WeatherSoap {
  def getWeather(city: Option[String]): Either[scalaxb.Fault[Any], Option[String]]
}


